name: bitsgap_mobx_auth
description: Bitsgap Mobx Auth
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  fast_immutable_collections: ^9.0.0
  mobx: ^2.1.4
  flutter_mobx: ^2.0.6+5
  mobx_widget: ^0.5.1
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  mobx_codegen: ^2.1.1

flutter:
  uses-material-design: true
